"""Vision models for computer vision tasks."""

from .convnext import (
    ConvNeXt,
    ConvNeXtBase,
    ConvNeXtLarge,
    ConvNeXtSmall,
    ConvNeXtTiny,
    convnext_base,
    convnext_large,
    convnext_small,
    convnext_tiny,
)
from .efficientnet import (
    EfficientNet,
    EfficientNetB0,
    EfficientNetB1,
    EfficientNetB2,
    EfficientNetB3,
    EfficientNetB4,
    EfficientNetB5,
    EfficientNetB6,
    EfficientNetB7,
    efficientnet_b0,
    efficientnet_b1,
    efficientnet_b2,
    efficientnet_b3,
    efficientnet_b4,
    efficientnet_b5,
    efficientnet_b6,
    efficientnet_b7,
)
from .resnet import (
    ResNet,
    ResNet18,
    ResNet34,
    ResNet50,
    ResNet101,
    ResNet152,
    resnet18,
    resnet34,
    resnet50,
    resnet101,
    resnet152,
)
from .vision_transformer import (
    VisionTransformer,
    ViT_B_16,
    ViT_H_14,
    ViT_L_16,
    vit_b_16,
    vit_b_32,
    vit_h_14,
    vit_l_16,
    vit_l_32,
)

__all__ = [
    # ResNet
    "ResNet",
    "ResNet18",
    "ResNet34",
    "ResNet50",
    "ResNet101",
    "ResNet152",
    "resnet18",
    "resnet34",
    "resnet50",
    "resnet101",
    "resnet152",
    # EfficientNet
    "EfficientNet",
    "EfficientNetB0",
    "EfficientNetB1",
    "EfficientNetB2",
    "EfficientNetB3",
    "EfficientNetB4",
    "EfficientNetB5",
    "EfficientNetB6",
    "EfficientNetB7",
    "efficientnet_b0",
    "efficientnet_b1",
    "efficientnet_b2",
    "efficientnet_b3",
    "efficientnet_b4",
    "efficientnet_b5",
    "efficientnet_b6",
    "efficientnet_b7",
    # Vision Transformer
    "VisionTransformer",
    "ViT_B_16",
    "ViT_L_16",
    "ViT_H_14",
    "vit_b_16",
    "vit_l_16",
    "vit_h_14",
    "vit_b_32",
    "vit_l_32",
    # ConvNeXt
    "ConvNeXt",
    "ConvNeXtTiny",
    "ConvNeXtSmall",
    "ConvNeXtBase",
    "ConvNeXtLarge",
    "convnext_tiny",
    "convnext_small",
    "convnext_base",
    "convnext_large",
]
