name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test import
      run: |
        python -c "import neural_arch; print('✓ Import successful')"
    
    - name: Run core tests
      run: |
        python -m pytest tests/test_tensor.py -v --tb=short --disable-warnings
    
    - name: Run additional tests (allow failures)
      run: |
        python -m pytest tests/test_linear_missing_coverage.py -v --tb=short --disable-warnings || true
    
    - name: Basic linting (relaxed)
      run: |
        pip install flake8
        flake8 src/ --count --statistics --max-line-length=120 --ignore=E203,W503,F401,F841,W291,W293,E501 || true